FinalEve/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using FinalEve.Models;

namespace FinalEve.Controllers
{
    public class AccessController : Controller
    {
       

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Models.UserInfo model)
        {
            using (var context = new ApplicationContext())
            {
                bool isValid = context.Logins.Any(x => x.Name == model.Name && x.Password == model.Password);
                if (isValid)
                {
                    FormsAuthentication.SetAuthCookie(model.Name, false);
                    return RedirectToAction("OrderInfo", "Order");
                }
                ModelState.AddModelError("", "Invalid Login");
                return View();
            }

        }
        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signup(Models.Login model)
        {
            using (var context = new ApplicationContext())
            {
                context.Logins.Add(model);
                context.SaveChanges();
            }
            return RedirectToAction("Login");
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

FinalEve/Controllers/CustomerController.cs
using FinalEve.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FinalEve.Controllers
{
    [Authorize]
    public class CustomerController:Controller
    {

        ApplicationContext db = new ApplicationContext();


        public ActionResult CustomerInfo()
        {
            return View(db.Customers.ToList());
        }

        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Insert(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("CustomerInfo");
            }

            return View(customer);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]

        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerInfo");
            }
            return View(customer);
        }
        public ActionResult Delete(int CustomerId)
        {
            try
            {
                var firstEntity = db.Customers.Where(c => c.CustomerId == CustomerId).FirstOrDefault();
                db.Customers.Remove(firstEntity);
                db.SaveChanges();
            }
            finally
            {

            }
            return RedirectToAction("CustomerInfo");
        }

    }
}

    

FinalEve/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -MVC_CRUD </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <table class="table">
        <tr>
            <td>@Html.ActionLink("Order", "OrderInfo", "Order")</td>
            <td>@Html.ActionLink("Customers", "CustomerInfo", "Customer")</td>
            @if (User.Identity.IsAuthenticated)
            {
                <td> <a>Hello- @User.Identity.Name</a></td>
                <td>@Html.ActionLink("Logout", "Logout", "Access")</td>
            }
            else
            {
                <td>@Html.ActionLink("Login", "Login", "Access")</td>
            }


        </tr>
    </table>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Final Exam</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>